'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''ImagePropertiesForm class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class ImagePropertiesForm

    '''<summary>
    '''lblSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSize As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSize As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWidth As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''spnWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnWidth As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''lblPixelWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPixelWidth As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeight As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''spnHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnHeight As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''lblPixelHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPixelHeight As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cellContarainTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellContarainTop As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''cellContarainSwitcher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellContarainSwitcher As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''cellContarainBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellContarainBottom As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ckbCreateThumbnail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbCreateThumbnail As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

    '''<summary>
    '''lblThumbnailFileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblThumbnailFileName As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txbThumbnailFileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbThumbnailFileName As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblImagePosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImagePosition As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbImagePosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbImagePosition As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''ckbWrapTextArroundImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbWrapTextArroundImage As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

    '''<summary>
    '''lblImageDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImageDescription As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txbDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDescription As Global.DevExpress.Web.ASPxEditors.ASPxTextBox
End Class
