'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''InsertImageForm class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class InsertImageForm

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.DevExpress.Web.ASPxPanel.ASPxPanel

    '''<summary>
    '''rblFromTheWeb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblFromTheWeb As Global.DevExpress.Web.ASPxEditors.ASPxRadioButton

    '''<summary>
    '''rblFromThisComputer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblFromThisComputer As Global.DevExpress.Web.ASPxEditors.ASPxRadioButton

    '''<summary>
    '''rpInsertImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpInsertImage As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditorRoundPanel

    '''<summary>
    '''lblImageUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImageUrl As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txbInsertImageUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbInsertImageUrl As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''SelectImageCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectImageCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''btnBrowse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBrowse As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''BrowsePopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BrowsePopup As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl

    '''<summary>
    '''PopupControlContentControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupControlContentControl1 As Global.DevExpress.Web.ASPxPopupControl.PopupControlContentControl

    '''<summary>
    '''SelectImageForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectImageForm As Global.SelectImageForm

    '''<summary>
    '''ckbSaveToServer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbSaveToServer As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

    '''<summary>
    '''lblBrowse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBrowse As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''uplImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uplImage As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditorUploadControl

    '''<summary>
    '''ucImagePropertiesForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucImagePropertiesForm As Global.ImagePropertiesForm

    '''<summary>
    '''ckbMoreImageOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbMoreImageOptions As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

    '''<summary>
    '''btnInsertImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInsertImage As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btnChangeImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChangeImage As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btnInsertImageCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInsertImageCancel As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''dxHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dxHiddenField As Global.DevExpress.Web.ASPxHiddenField.ASPxHiddenField
End Class
