'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''InsertTableForm class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class InsertTableForm

    '''<summary>
    '''MainPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainPanel As Global.DevExpress.Web.ASPxPanel.ASPxPanel

    '''<summary>
    '''PanelContent1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelContent1 As Global.DevExpress.Web.ASPxPanel.PanelContent

    '''<summary>
    '''rpSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpSize As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditorRoundPanel

    '''<summary>
    '''HtmlEditorRoundPanelContent1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HtmlEditorRoundPanelContent1 As Global.DevExpress.Web.ASPxHtmlEditor.HtmlEditorRoundPanelContent

    '''<summary>
    '''lblSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSize As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblColumns As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''spnColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnColumns As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''lblRows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRows As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''spnRows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnRows As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''lblWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWidth As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbWidth As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''txbWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbWidth As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''cmbWidthType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbWidthType As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''ckbColumnsEqualWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbColumnsEqualWidth As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

    '''<summary>
    '''lblHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeight As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbHeight As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''txbHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbHeight As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''cmbHeightType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbHeightType As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''rpLayout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpLayout As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditorRoundPanel

    '''<summary>
    '''HtmlEditorRoundPanelContent4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HtmlEditorRoundPanelContent4 As Global.DevExpress.Web.ASPxHtmlEditor.HtmlEditorRoundPanelContent

    '''<summary>
    '''lblLayout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLayout As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblPadding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPadding As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''spnPadding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnPadding As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''lblAlign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlign As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbAlign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAlign As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblSpacing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpacing As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''spnSpacing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnSpacing As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''rpAppearance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpAppearance As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditorRoundPanel

    '''<summary>
    '''HtmlEditorRoundPanelContent3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HtmlEditorRoundPanelContent3 As Global.DevExpress.Web.ASPxHtmlEditor.HtmlEditorRoundPanelContent

    '''<summary>
    '''lblAppearance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppearance As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblBorderColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBorderColor As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txbBorderColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbBorderColor As Global.DevExpress.Web.ASPxEditors.ASPxColorEdit

    '''<summary>
    '''lblBorderSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBorderSize As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''spnBorderSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnBorderSize As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''lblBackgroundColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBackgroundColor As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txbBackgroundColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbBackgroundColor As Global.DevExpress.Web.ASPxEditors.ASPxColorEdit

    '''<summary>
    '''ckbAccessibility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbAccessibility As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

    '''<summary>
    '''rpAccessibility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpAccessibility As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditorRoundPanel

    '''<summary>
    '''HtmlEditorRoundPanelContent2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HtmlEditorRoundPanelContent2 As Global.DevExpress.Web.ASPxHtmlEditor.HtmlEditorRoundPanelContent

    '''<summary>
    '''lblHeaders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeaders As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbHeaders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbHeaders As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCaption As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txbCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCaption As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSummary As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txbSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbSummary As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''btnOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOk As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.DevExpress.Web.ASPxEditors.ASPxButton
End Class
