'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''TableColumnPropertiesForm class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class TableColumnPropertiesForm

    '''<summary>
    '''MainPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainPanel As Global.DevExpress.Web.ASPxPanel.ASPxPanel

    '''<summary>
    '''PanelContent1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelContent1 As Global.DevExpress.Web.ASPxPanel.PanelContent

    '''<summary>
    '''rpSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpSize As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditorRoundPanel

    '''<summary>
    '''HtmlEditorRoundPanelContent1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HtmlEditorRoundPanelContent1 As Global.DevExpress.Web.ASPxHtmlEditor.HtmlEditorRoundPanelContent

    '''<summary>
    '''lblSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSize As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWidth As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbWidth As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''txbWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbWidth As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''cmbWidthType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbWidthType As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeight As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbHeight As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''txbHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbHeight As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''cmbHeightType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbHeightType As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''rpLayout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpLayout As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditorRoundPanel

    '''<summary>
    '''HtmlEditorRoundPanelContent4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HtmlEditorRoundPanelContent4 As Global.DevExpress.Web.ASPxHtmlEditor.HtmlEditorRoundPanelContent

    '''<summary>
    '''lblAlign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlign As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblHorizontalAlign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHorizontalAlign As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbAlign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAlign As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lblVerticalAlign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVerticalAlign As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbVAlign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbVAlign As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''rpAppearance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpAppearance As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditorRoundPanel

    '''<summary>
    '''HtmlEditorRoundPanelContent3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HtmlEditorRoundPanelContent3 As Global.DevExpress.Web.ASPxHtmlEditor.HtmlEditorRoundPanelContent

    '''<summary>
    '''lblAppearance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppearance As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblBackgroundColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBackgroundColor As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txbBackgroundColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbBackgroundColor As Global.DevExpress.Web.ASPxEditors.ASPxColorEdit

    '''<summary>
    '''ckbApplyForAllElements control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbApplyForAllElements As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

    '''<summary>
    '''btnChange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChange As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.DevExpress.Web.ASPxEditors.ASPxButton
End Class
