'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class DefaultVertical

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form2 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''GE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GE As Global.DevExpress.Web.ASPxGlobalEvents.ASPxGlobalEvents

    '''<summary>
    '''ProgressControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProgressControl As Global.DevExpress.ExpressApp.Web.Controls.ASPxProgressControl

    '''<summary>
    '''PlaceHolder1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlaceHolder1 As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''LogoLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogoLink As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''TIC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TIC As Global.DevExpress.ExpressApp.Web.Controls.ThemedImageControl

    '''<summary>
    '''SAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SAC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

    '''<summary>
    '''ShC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

    '''<summary>
    '''NC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationActionContainer

    '''<summary>
    '''TRP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TRP As Global.DevExpress.Web.ASPxRoundPanel.ASPxRoundPanel

    '''<summary>
    '''PanelContent1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelContent1 As Global.DevExpress.Web.ASPxPanel.PanelContent

    '''<summary>
    '''VTC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VTC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

    '''<summary>
    '''DAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DAC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

    '''<summary>
    '''TB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

    '''<summary>
    '''VIC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VIC As Global.DevExpress.ExpressApp.Web.Controls.ViewImageControl

    '''<summary>
    '''VCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VCC As Global.DevExpress.ExpressApp.Web.Controls.ViewCaptionControl

    '''<summary>
    '''VHC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VHC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationHistoryActionContainer

    '''<summary>
    '''RNC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RNC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

    '''<summary>
    '''EMA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EMA As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder

    '''<summary>
    '''ErrorInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorInfo As Global.DevExpress.ExpressApp.Web.Templates.Controls.ErrorInfoControl

    '''<summary>
    '''VSC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VSC As Global.DevExpress.ExpressApp.Web.Controls.ViewSiteControl

    '''<summary>
    '''QC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QC As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.QuickAccessNavigationActionContainer

    '''<summary>
    '''InfoMessagesPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InfoMessagesPanel As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''AIC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AIC As Global.DevExpress.ExpressApp.Web.Controls.AboutInfoControl
End Class
